version: '3.0'
services:

  # TODO: Might want to run dockergen in separate container?
  # TODO: Run letsencrypt container?
  nginx:
    image: jwilder/nginx-proxy:alpine-0.6.0
    networks:
      misago:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # TODO: Might be better to use `DOCKER_HOST`
      - /var/run/docker.sock:/tmp/docker.sock:ro

  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      misago:
    env_file:
      - postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    networks:
      misago:
    volumes:
      - redis:/data

  misago:
    build: misagodocker
    restart: unless-stopped
    volumes:
      - misago-media:/misago/media
    networks:
      misago:
        aliases:
          - misago
    env_file:
      - misagodocker.env
      - postgres.env
    depends_on:
      - postgres
      - nginx
      - redis
    tty: true


volumes:
  pgdata:
  redis:
  misago-media:

networks:
  misago:
